config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'feedbacks#index'
  resources :feedbacks, only: [:index, :show, :new, :create] do
    resources :responses, only: [:new, :create, :show]
  end
  resources :questions, only: [] do
    collection do
      get :insert
    end
  end
  resources :responses, only: [:new, :create, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :response

  validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  has_many :questions, inverse_of: :feedback
  has_many :responses, inverse_of: :feedback

  accepts_nested_attributes_for :questions

  DEFAULT_QUESTIONS = [
    'What is your favorite book?',
    'Who is your favorite band?',
    'What is your favorite food?'
  ]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :feedback
  has_many :answers, inverse_of: :question
end

app/models/respondent.rb
class Respondent < ApplicationRecord
  has_one :response
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :feedback
  has_many :answers
  belongs_to :respondent

  accepts_nested_attributes_for :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  def index
    @feedbacks = Feedback.includes(:questions)
  end

  def show
  end

  def new
    @feedback = Feedback.new
    Feedback::DEFAULT_QUESTIONS.each do |question|
      @feedback.questions.build(question: question)
    end
  end

  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to feedbacks_path, notice: 'Feedback was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    def feedback_params
      params.fetch(:feedback).permit(:name, questions_attributes: [:question, :custom])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def insert
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]
  before_action :set_feedback, only: [:new, :create]

  def index
    @responses = Response.all
  end

  def show
  end

  def new
    @response = @feedback.responses.new
    @questions = @feedback.questions
    @questions.each do |question|
      @response.answers.build(question_id: question.id)
    end
  end

  def create
    @response = @feedback.responses.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to new_feedback_response_path(@response.feedback), notice: 'Response was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_response
      @response = @feedback.responses.find(params[:id])
    end

    def set_feedback
      @feedback = Feedback.find(params[:feedback_id])
    end

    def response_params
      params.fetch(:response).permit(:feedback_id, answers_attributes: [:answer, :question_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def has_error(resource, field_name)
    return 'has-error' if resource.errors[field_name].present?
  end
end

app/views/application/_footer.html.slim
nav.navbar.navbar-default.margin-top
  .container-fluid
    .navbar-header
      =link_to '#', class: 'navbar-brand' do
        | &copy; Feedbacks

app/views/application/_navigation.html.slim
nav.navbar.navbar-default.header
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#navbar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to 'Feedback Home', root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          =link_to '#' do
            | Responses
            span.sr-only (current)

app/views/application/_question_form_text_field_template.html.slim
.form-group
  =text_field_tag "feedback[questions_attributes][#{Time.now.to_i.to_s + rand(0...3262010).to_s}][question]", '', class: 'form-control custom_question'

app/views/feedbacks/_return_button.html.slim
=link_to 'Create a New Survey Feedback', new_feedback_path, class: 'btn btn-primary btn-sm'

app/views/feedbacks/index.html.slim
.row
  .col-md-5
    h3 List of Feedbacks
  .col-md-3.text-right
    =link_to 'Create a New Survey Feedback', new_feedback_path, class: 'btn btn-primary btn-sm'
.row
  .col-md-8
    table.table.table-bordered.table-condensed
      tr
        td.col-md-3 Survey Feedback Name
        td.col-md-2 No. of Questions
        td.col-md-2 No. of Responses
        td.col-md-5 Shareable Link
      - @feedbacks.each do |feedback|
        tr
          td =link_to new_feedback_response_url(feedback) do
            = feedback.name.blank? ? "Feedback ##{feedback.id}" : feedback.name
          td =feedback.questions.count
          td =feedback.responses.count
          td
            .input-group
              span.input-group-btn
                button.btn.btn-default.shareable_button type="button" class="btn btn-warning btn-sm"  Copy
              input.form-control.input-sm value="#{new_feedback_response_url(feedback)}" type="text"

app/views/feedbacks/new.html.slim
.row
  .col-md-5
    h3 Create a Survey Feedback
  .col-md-3.text-right
    = render 'return_button'
.row
  .col-md-8
    =form_for @feedback do |f|
      .form-group
        =f.label :name, 'Describe Survey Feedback'
        =f.text_area :name, class: 'form-control', placeholder: 'Survey Feedback description'
      .form-group
        =link_to 'Add Addtional Question to Survey Feedback', insert_questions_path, class: 'btn btn-primary btn-sm', remote: true
      .questions
        = f.fields_for :questions do |n|
          .form-group
            =n.text_field :question, class: 'form-control', readonly: true
            =n.hidden_field :custom, value: false
      =f.submit 'Save Survey', class: 'btn btn-primary btn-sm'

app/views/feedbacks/show.html.slim
.row
  .col-md-8
    h3 =@feedback.name
.row
  .col-md-8
    - form_for :feedback do |f|
      - @feedback.questions.each do |question|
        .form-group
          =f.text_field :answer
          =f.hidden_field question.id

app/views/layouts/application.html.slim
doctype html
html
  head
    title Survey App
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield(:jsapi)
    = csrf_meta_tags
  body
    = render 'navigation'
    .container-fluid.margin-bottom
      = yield
    = render 'footer'

app/views/questions/insert.js.erb
$(".questions")
  .append("<%= j render 'question_form_text_field_template' %>");

app/views/responses/new.html.slim
.row
  .col-md-8
    h3 =@feedback.name || ''
.row
  .col-md-8
    = form_for [:feedback, @response] do |f|
      = f.hidden_field :feedback_id, value: @feedback.id
      = f.fields_for :answers, @response.answers.each do |n|
        .form-group class="#{has_error(n.object, :answer)}"
          =n.label :answer, n.object.question.question
          =n.text_area :answer, rows: '2', class: 'form-control'
          =n.hidden_field :question_id, value: n.object.question.id
          - if n.object.question.custom?
            p.help-block This question was added by the administrator
      =f.submit "Submit Response", class: 'btn btn-primary'